### ISSUE TITLE
fragments rendered with layout [Rails 5]

### ISSUE THREAD

**Issue by MichaelSp** [johnsonj/progressive_render#17]
I don't know if this is a rails 5 issue, but here in my rails 5 app this doesn't work.

I've debugged a bit and found out that this method is not being called:

```
ProgressiveRender::Rails::ViewRenderer#render_fragment
```

I think it is required for progressiv_render gem to call this render_fragment method, because here the layout: false is being passed.

**Comment by MichaelSp** [comment]
My fault. Forgot to call `progressive_render` in the end of the controller action.

Maybe it's easier to add something like this to `ApplicationController`

```
class ApplicationController < ActionController::Base
    def default_render
       params[:load_partial].nil? ? super :  progressive_render
    end
end
```

or even better?

```
class ApplicationController < ActionController::Base
    def default_render
       progressive_render
    end
end
```

**Comment by johnsonj** [comment]
Thanks for the suggestion @MichaelSp, I didn't go that route because I wanted to reduce my regression surface but I do really like your suggestion of basing it on the load_partial param. Will consider that for the next release.
