### ISSUE TITLE
DEPRECATION WARNING / SCSS file naming convention

### ISSUE THREAD

**Issue by spaquet** [johnsonj/progressive_render#24]
Just installed Progressive_render in a Rails 5.0.2 app and got the following warning message:

`DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename [...]/progressive_render.css.scss to [..]/progressive_render.scss.`

I think this is pretty straightforward to fix as this is only a naming convention change.

**Comment by johnsonj** [comment]
Fixed by #25

**Comment by johnsonj** [comment]
Fix released in `0.7.0`
