### ISSUE TITLE
problem with progressive rendering when use search/filter

### ISSUE THREAD

**Issue by Rubioli** [johnsonj/progressive_render#28]
Great `gem` 👍 

`progressive_render` works on all my views beside one. In my `posts#index` view, I use filter to filter in my posts.

*Some part of my `posts#index`:*
```
#results
      = render partial: 'posts/list', locals: { posts: @posts }
```

*My `posts/list`:*
```
= progressive_render do
  - posts.each do |post|
     = post.title
```

*My `index.js.erb`:*
```
<% js = escape_javascript(render(partial: 'posts/list', locals: { posts: @posts }) ) %>
$("#results").html("<%= js %>");
```

My problem now is that when I search for a word, results are not showing and the *loading* part is just loading.

How can I fix this?

Thanks in advanced!

**Comment by johnsonj** [comment]
I'm guessing that the event to load the partial content is never getting kicked off. Can you try raising the event `progressive_render:end` after you set the HTML?

`index.js.erb`
```
...
$("#results").html("<%= js %>");
$(document).trigger('progressive_render:end')
```

**Comment by Rubioli** [comment]
Thanks for your help :) 

Adding `$(document).trigger('progressive_render:end')` works great 👍
