### ISSUE TITLE
Performing javascripts inside progressive_reder

### ISSUE THREAD

**Issue by rafaltrojanowski** [johnsonj/progressive_render#31]
Nice gem!

However, I've noticed that javascript is not being performed properly when I wrap code in the block:

```
<%=progressive_render do %>
<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
    alert("test")
  });
</script>
<% end %>
```
Is it something with my setup or this feature is not supported?

**Comment by johnsonj** [comment]
Hey @rafaltrojanowski, thanks! 

The gem injects content from that block via [jQuery.html(..)](https://api.jquery.com/html/). If that doesn't execute script contents then perhaps there's more we can [do here?](https://github.com/johnsonj/progressive_render/blob/master/vendor/assets/javascripts/progressive_render.js.coffee#L19)

Have you tried just `alert("test")` in your script block (w/o the turbolinks:load event)? The gem doesn't trigger any turbolinks events. It does raise `progressive_render:end` if you need to execute code on that event.

**Comment by rafaltrojanowski** [comment]
> Have you tried just alert("test") in your script block (w/o the turbolinks:load event)?

It helps :)

However, observed that to make it fully work in cases when user switch between pages (with turbolinks) we would need to use it with document ready:

```
<%=progressive_render do %>
  <script type="text/javascript">
    $(document).ready(function(){
      alert("hi there!")
   });
  </script>
<% end %>
```

I think I'm satisfied with this solution. I guess that support for turbolinks requires some additional work.
Thanks for your help @johnsonj!

**Comment by johnsonj** [comment]
sweet!
